name: Python package

on:
  push:
    workflow_dispatch:
      inputs:
        testType:
          description: 'Type of test to run'
          required: true
          default: 'test'
          type: choice
          options:
          - test
          - test_integration
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make env
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          make ${{ github.event.input.testType }}
